### ISSUE TITLE
Don't use base32 encoded sha256 hashes for Python packages

### ISSUE THREAD

**Issue by prusnak** [ryantm/nixpkgs-update#106]
Use base-16 (hex) encoded ones. That way one can compare it directly (by eye) with the hashes published on PyPI download page.

**Comment by ryantm** [comment]
@FRidh @dotlambda  do you agree that this would be good?

**Comment by dotlambda** [comment]
It would have the additional benefit of not conflicting with updates made by @FRidh's script for updating Python packages.

**Comment by bhipple** [comment]
Personally, I'd prefer base32 over base16, because:

- They're shorter
- `nix-prefetch-url` returns base32 
- If a user does a manual TOFU update with a bogus hash, the `nix` tooling will tell him the base32 hash.
- The pypi base16 hash can be easily re-validated with `nix-hash --type sha256 --to-base16 <hash>` if a user wants to verify it
- Most other packages in NixPkgs are using base32, including many python packages coming from github/gitlab/elsewhere that are conventionally using base32
- Keeping it consistent on base32 means bots like nixpkgs-update and @fridh's script don't need to be customized on "pypi python package" vs. "not a pypi python package" for determining which encoding to use.

All that said, I don't feel terribly strongly about it one way or the other and care more about consistency than anything else; I'll happily defer to either community decision, but whatever we decide we should document it in the python manual section.

**Comment by FRidh** [comment]
> All that said, I don't feel terribly strongly about it one way or the other and care more about consistency than anything else; I'll happily defer to either community decision, but whatever we decide we should document it in the python manual section.

I agree and suggest we use base32 throughout Nixpkgs.

**Comment by FRidh** [comment]
By the way, I just want to add that without CI enforcing this, I don't think we should actively push or require people to use base32 everywhere. It's good to have, and so let's fix our tooling to use it, but leave it at that until we can actually enforce it.
