### ISSUE TITLE
buildGoModule: modSha256 -> vendorSha256

### ISSUE THREAD

**Issue by Mic92** [ryantm/nixpkgs-update#203]
In https://github.com/NixOS/nixpkgs/pull/86376 we renamed modSha256 to vendorSha256. No new packages with modSha256 will be accepted hence you can just rename the attribute to the new version.

**Comment by Mic92** [comment]
One thing to add, if `vendorSha256 = null;` than it should stay null because in this case an internal vendor directory is used.

**Comment by NickHu** [comment]
I've encountered a very strange (possible) bug in one of my PRs: https://github.com/NixOS/nixpkgs/pull/85898

If you simply use `vendorSha256` instead of `modSha256`, the package will still build but there won't be any binaries in the output! I had a quick look at the Go module infrastructure but couldn't make much sense of it, but I think this isn't a case of simply a rename.

**Comment by Mic92** [comment]
@NickHu did you rebase on master before doing this?

**Comment by NickHu** [comment]
It was a while ago, I did it after I saw the deprecation warning but possibly before this commit. Anyway it works now so my concerns have largely been resolved. Not really sure what happened - was the deprecation warning introduced before the expression was stable maybe?
