### ISSUE TITLE
Updates broken

### ISSUE THREAD

**Issue by bhipple** [ryantm/nixpkgs-update#235]
From the logs, it looks like the bot is having some permission issues and hasn't sent a PR for a while:

```
/nix/store/333six1faw9bhccsx9qw5718k6b1wiq2-stdenv-linux/setup: line 796: /tmp/env-vars: Permission denied
```
https://r.ryantm.com/log/2020-10-14.log

**Comment by ryantm** [comment]
Yep, I've been trying to fix it. There's been a myriad of things wrong so far:

- [x] python updatescript was broken
- [ ] something about python updates is crashing ( I sort of fixed this by letting it proceed to the next type of updater if the python one crashes)
- [x] If an updatescript didn't change anything, it was still calculating the outpaths, so a broken updatescript made it run super slowly
- [ ] I just saw it crash because the connection timed out while accessing the National Vulnerability Database, probably need to add retries there.

**Comment by ryantm** [comment]
Oh, I don't think that permission denied error is relevant. I see that with nix generally https://github.com/NixOS/nix/issues/920 and I think it was in the logs before without issue.

**Comment by ryantm** [comment]
I'm disabling the CVE feature for now, since it seems to be getting connection timeouts for this URL:

https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2002.meta

**Comment by ryantm** [comment]
Yay we got an update https://github.com/NixOS/nixpkgs/pull/100541 !

**Comment by ryantm** [comment]
@doronbehar Oh, right. That was another issue: the python-unstable branch was removed. I think I fixed that error too https://github.com/ryantm/nixpkgs-update/commit/93cc3604385cd2520b03df814066bf9ea6aca373

**Comment by ryantm** [comment]
I think it is safe to say updates are generally unbroken now. 

Follow up issue for fixing CVE feature: https://github.com/ryantm/nixpkgs-update/issues/238
