### ISSUE TITLE
Are binary checks the responsibility of nixpkgs-update?

### ISSUE THREAD

**Issue by raboof** [ryantm/nixpkgs-update#260]
Shouldn't we encourage projects to add those in their `installCheckPhase`, like https://github.com/NixOS/nixpkgs/pull/119636 ?

**Comment by ryantm** [comment]
@raboof I agree that it would be better for those checks to be upstreamed. If there was some default version check that checked the version of everything in the bin directory, that would probably be quite useful. 

It may be preferable to use `passthru.tests` instead of `installCheckPhase`, since the later introduces overhead of every build. Also, `passthru.tests` can be executed independently of the build.

**Comment by ryantm** [comment]
nixpkgs-update and OfBorg run `passthru.tests`

**Comment by raboof** [comment]
> It may be preferable to use `passthru.tests` instead of `installCheckPhase`, since the later introduces overhead of every build. Also, `passthru.tests` can be executed independently of the build.

Took me a while to figure out how exactly, so proposed https://github.com/NixOS/nixpkgs/pull/119731

**Comment by raboof** [comment]
> It may be preferable to use `passthru.tests` instead of `installCheckPhase`, since the later introduces overhead of every build. Also, `passthru.tests` can be executed independently of the build.

let's discuss this in https://github.com/NixOS/nixpkgs/pull/119731#discussion_r615373508

**Comment by ryantm** [comment]
I think I will get rid of the binary checks. I don't think they work that well, are looked at much, and operationally they stall updates sometimes the programs hang around in a way it doesn't know how to kill.

**Comment by Artturin** [comment]
I look at the binary checks, and I can merge the pr without even building it if those pass and the upstream commits are okay.

**Comment by ryantm** [comment]
I removed binary checking.
