### ISSUE TITLE
Allow adding new versions on top of existing open PR

### ISSUE THREAD

**Issue by ryantm** [ryantm/nixpkgs-update#64]
https://github.com/ryantm/nixpkgs-update/issues/61#issuecomment-406393221

**Comment by rhendric** [comment]
I'd like to work on this.

Going a level down on intended behavior, does the below sound good?
* Do nothing if the package version on the existing PR branch equals the version obtained by updating the package
* Create a new commit directly over the current head of the base branch that updates to the new version and force-push it to the PR branch, eradicating the older commit
* Update the title of the PR to reflect the new version change
* Add a new comment to the PR containing all the output usually contained in the initial PR comment

**Comment by ryantm** [comment]
@rhendric I'm not sure about the what base commit to use for the new commit. Ideally, you'd use the most recent merge-base of master and staging, but I'm worried that might cause GitHub to do something dumb. Using the existing base commit should be safe though, so probably that is a good idea.

The rest sounds great.

Is it possible we could get ourselves into a loop on some packages where they never get merged before a new version comes out?

**Comment by rhendric** [comment]
Sorry for the interrupted conversation! I'm usually more responsive than this; life snuck up on me and I had to ignore my OSS threads for a little while.

I think I misunderstood what was going on with the commits—I completely missed the merge-base of master and staging logic. That said, I would prefer if we used the newest possible merge-base and not the merge-base used originally by the PR, in order to crush many of the merge conflicts that can appear over the lifetime of a long-lived PR. I'd be surprised if this caused issues for GitHub by itself, as long as the PR branch is reused.

The loop you mention *does* seem possible, and that's one reason I wanted to discuss the ideal workflow ahead of time. It's only a problem if a human starts engaging with the PR (by testing it, say), right? I could imagine doing something like not updating the PR with new versions if there have been any human commenters on it. I could also imagine doing nothing because the expected number of packages that update more frequently than they can be reviewed is low enough to be put on a special list if necessary. Thoughts?

**Comment by ryantm** [comment]
Yeah, seems like using the newest merge base would be nice. I think recently, I actually accidentally tested this is fine because I ran r-ryantm for a brief time with batch more off and it force pushed new merg based commits to existing PRs. Maybe this feature will be easier to add then expected!

I think we should worry more about that loop if it actually starts happening.

**Comment by rhendric** [comment]
Great, thanks for the guidance!
